image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: kJ5a/VtrxfhiYu6bsH3CXImLUhOZzNtYk1RbcjUILmitx6F4bU3zJL+HAtw5XWQS

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: artifacts\*.nupkg

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
